<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Đổi mật khẩu </h3>
    </div>
    <!-- /.col-lg-12 -->
</div>

<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">            
            <div class="panel-heading">
                 <div class="row">
                     <div class="col-lg-2" style="text-align:center;width: 9%;padding-right: 0px;">
                         
                     </div>
                     
                 </div>
            </div>
            <div class="panel-body">
                <div class="table-reponsive">
                   <div class="panel-body">
                                            <div class="row">
                                                <div class="col-lg-12">
                                                    <form role="form" action="<?php echo $this->baseUrl()?>/default/sysuser/list" method="POST"  name="changepass" onsubmit="return checkinputpass();">

                                                         <div class="form-group">
                                                            <div class="row">
                                                                <div class="col-lg-4">
                                                                    <label>Mật khẩu mới(*)</label>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <input class="form-control" name="newpassword" id="newpassword" type="password" value="">
                                                                </div>

                                                            </div>
                                                        </div>
                                                        <div class="form-group">
                                                            <div class="row">
                                                                <div class="col-lg-4">
                                                                    <label>Nhập lại mật khẩu mới(*)</label>
                                                                </div>
                                                                <div class="col-lg-6">
                                                                    <input class="form-control" type="password" name="renewpassword" id="renewpassword" value="">
                                                                </div>
                                                            </div>
                                                        </div> 
                                                        <div class="col-lg-12">
                                                            <div class="form-group">
                                                                <div class="row">
                                                                    <div class="col-lg-4">
                                                                    </div>
                                                                    <div class="col-lg-6">
                                                                        <button type="submit" id="editpass" name="editpass" class="btn btn-primary">Lưu</button>
                                                                    </div>
                                                                </div>  
                                                            </div>
                                                        </div> 
                                                     </form>
                                                    </div> 
                                                </div>
                                            </div>
<!--                                        ////-->
                </div>
            </div>
    </div>
</div>
<script type="text/javascript">
    
</script>
<script type="text/javascript">
       function checkinputpass() {        
        var frm1 = window.document.changepass;
        
        if ($("#oldpassword").val() == "") {
            bootbox.alert("Vui lòng nhập mật khẩu!");
            return false;
        }        
        if ($("#newpassword").val() == "") {
            bootbox.alert("Vui lòng nhập mật khẩu xác nhận!");
            return false;
        }        
        if(frm1.renewpassword.value != frm1.newpassword.value )
        {
            bootbox.alert("Mật khẩu xác nhận không chính xác!");
            return false;
        }
//        var oldpassword= $('#oldpassword').val();
//        var flag;
//        $.ajax({
//            type:'post',
//            url:'<?php // echo $this->baseUrl()?>/default/sysuser/checkoldpassword/pass/'+oldpassword,
//            async:false,
//            dataType:'json',
//            success:function(data){
//                if(data[0].code==1){
//                    flag=false;
//                } else {
//                    flag=true;
//                }
//            }
//        });
//        if(flag==true){
//            bootbox.alert("Mật khẩu cũ không đúng.Vui lòng kiểm tra và nhập lại.");
//            return false;
//        };
         var params = {
                        id: "<?php echo $this->item->getId() ?>",
                        password: $("#newpassword").val()
         }; 
         $.post("<?php echo $this->baseUrl().'/default/sysuser/changepassword1'?>", params, function(datas) {                            
                var items = eval(datas);
                var jItem = items[0];
                if (jItem.html != '') 
                {

                    window.location = jItem.html;
                } 
                else 
                {
                    if (errorMessage != '' && errorMessage != null) {
                        alert(errorMessage);
                    }
                }
            }); 
        return true;
    }
    </script>
    