<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Thêm ấn chỉ</h3>
    </div>    
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-10">
                        <form  method="POST" name="Addmasterprint" onsubmit=" return checkinput();">                                    
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Mã Code(*)</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control" name="code" id="code" value="<?php echo $this->item->getCode(); ?>">
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Tên ấn chỉ(*)</label>
                                    </div>
                                    <div class="col-lg-6">
                                            <textarea  name="name" id="name" type="text" class="form-control" cols="100" rows="3"><?php echo $this->item->getName(); ?></textarea>    
                                    </div>  
                                    
                                </div>
                            </div>
                             <div class="form-group">
                                    <div class="row">
                                    <div class="col-lg-3">
                                        <label>Ghi chú</label>
                                    </div> 
                                        <div class="col-lg-6">
                                            <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="5"><?php echo $this->item->getComment(); ?></textarea>    
                                        </div>  
                                    </div>                                
                             </div>
                             <div class="row">
                                <div class="col-lg-6">                      
                                        <div class="form-group">
                                            <div class="row">
                                                 <div class="col-lg-9">
                                                    <button type="submit" name="import" id="import" class="btn btn-primary">Thêm mới</button>
                                                    <button type="reset" name="reset" id="reset"class="btn btn-default">Đặt lại</button> 
                                                 </div>   
                                            </div>
                                        </div> 
                                </div></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>
<script type="text/javascript">
            $(document).ready(function () { 
                $('#reset').click(function(){
                        $('#name').text("");
                        $('#comment').text("");
                        $('#name').focus();
                });
            });
</script>
<script type="text/javascript">
    document.forms['Addmasterprint'].code.focus();
    function set_focus() {
        document.forms['Addmasterprint'].code.focus();
    }
    var flag=true;
    var flag1=true;
    function checkinput() {
        var frm = window.document.Addmasterprint;
        if (frm.code.value == "") {
            bootbox.alert("Vui lòng nhập mã code");
            return false;
        };
        if(isNaN(frm.code.value)== false){
            bootbox.alert("Vui lòng nhập mã code bằng chữ");
            return false;
        }  
        if (frm.name.value == "") {
            bootbox.alert("Vui lòng nhập tên ấn chỉ");
            return false;
        };
        if(isNaN(frm.name.value)== false){
            bootbox.alert("Vui lòng nhập tên ấn chỉ bằng chữ");
            return false;
        }
        var flag;
        var code= $('#code').val();
        $.ajax({
            type:'post',
            url:'<?php echo $this->baseUrl()?>/default/masterprint/checkcode/code/'+code,
            async:false,
            dataType:'json',
            success:function(data){
                if(data[0].code==1){
                    flag=false;
                } else {
                    flag=true;
                }
            }
        });
        if(flag==false){
            bootbox.alert("Mã code này đã tồn tại. Vui lòng kiểm tra và nhập lại.");
            return false;
        };
       
      return true;
    }
</script>