
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Thông tin vi phạm - xử lý </h3>      
    </div>    
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">             
           <div class="panel-heading">
                 <div class="row">
                 </div>
            </div>
            <div class="panel-body">
                <div class="table-reponsive">
                    <div id="jqxgrid">
                    </div>
                </div>
            </div>
            
            <div class="row">
                <div class="col-lg-12">
                    <div id="jqxgrid"></div>
                    <div style="visibility: hidden;" id="jqxWidget">
                        <div id="window" hidden="true">
                                <div>
                                    <h5>(**)</h5>
                                </div>
                                <div>
                                    <center> 
                                        <div class="row">
                                            <h5><B>DANH SÁCH ẤN CHỈ VÀ SERIAL CHƯA XỬ PHẠT THEO PHÒNG BAN</B></h5>
                                        </div>
                                    </center>
                                    <div class="panel panel-default">             
                                        <div class="panel-heading">
                                        </div>
                                        <div class="panel-body">
                                            <div id="jqxgrid_recovery">
                                            </div> 
                                        </div>
                                        <div class="panel-heading">
                                            <div class="row">
                                                <center>
                                                <!--<div style="font-family: Verdana; font-size: 12px; width: 700px; margin-left: 20px; float: left;">-->
                                                        <form role="form" method="POST" name="Addxuphat" onsubmit="return checkserialxuphat();"> 
                                                            <input type="text" name="listserialprint" id="listserialprint"/>
                                                            <button type="reset" id="lamlai" class="btn btn-default">Làm lại</button> 
                                                            <input type="submit"  id="xuphat" value ="Lưu" class="btn btn-default">
                                                         </form>
                                                </center>
                                                <!--</div>-->
                                            </div>
                                        </div>
                                        
                                    </div>
                                </div>
                        </div>
                    </div>
                </div>                
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function () {
        $("#jqxWidget").css('visibility', 'visible');
    });
</script> 

<script type="text/javascript">
    function addEventListeners() {
          $('#showWindowButton').mousedown(function () {
              $('#window').jqxWindow('open');
              $('#window').jqxWindow('focus');
          });            
      }
      function createElements() {           
          $('#window').jqxWindow({
              resizable: true,
              isModal: true,
              width: 800,
              height: 500,
              minWidth: 800,
              minHeight: 500
          });           
      }
    function jsdelete(sys_department_id)
    {
         createElements();
            $('#window').jqxWindow('open');
            $('#window').jqxWindow('focus'); 
            // prepare the data
            var data = new Array();
            var arraylistprint_serial = new Array();var l=0;
            $.ajax({
                type:'post',
                url:"<?php echo $this->baseUrl().'/master/DocViolationshandling/secviceserialdepartmentmasterprint/id/'?>"+sys_department_id,
                async:false,
                dataType:'json',
                success:function(data1){
                    for(var i=0; i<data1.length;i++){
                        data.push(data1[i].serial_allocation);
//                        alert(data);
                    }
                }
            });
            /////
            var source1 =
            {
                datatype: "json",
                datafields:
                [
                    {name: 'master_print_id',type:'int'},
                    {name: 'name_print',type:'string'},
                    {name: 'serial',type:'string'}
                ],
                addrow: function (rowid, rowdata, position, commit) {
                    commit(true);
                },
                deleterow: function (rowid, commit) {
                    commit(true);
                },
                updaterow: function (rowid, newdata, commit) {
                    commit(true);
                },
                url:"<?php echo $this->baseUrl().'/master/DocViolationshandling/secviceprintdepartment/id/'?>"+sys_department_id,
                        //sortcolumn: 'order',
                        sortdirection: 'asc'
            };
            var dataAdapter = new $.jqx.dataAdapter(source1);
            var createGridEditor = function(row, cellValue, editor, cellText, width, height)
                {   
                    var id = $("#jqxgrid_recovery").jqxGrid('getrowid', 0); 
                    var rowscount = $("#jqxgrid_recovery").jqxGrid('getdatainformation').rowscount; 
                    for(var j = id; j< rowscount;j++){
                        if (row == j) {
                            editor.jqxListBox({theme: theme, checkboxes: true,width: width, height: 30, source:data[j] });
                        }
                    }
                }
            var initGridEditor = function (row, cellValue, editor, cellText, width, height) {
            for(var j =0; j<3;j++){
                       if (row == j) {
                       editor.jqxListBox('selectItem', cellValue);
                   }
                   }  
               }
            var gridEditorValue = function (row, cellValue, editor) {
                return editor.val();
            }
            $("#jqxgrid_recovery").jqxGrid(
            {
                width: '100%',
                height: 350,
                source: dataAdapter,
                showtoolbar: true,
                theme: 'bootstrap',
                pageable: true,
                showfilterrow: true,
                filterable: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                editable: true,
                selectionmode: 'multiplecellsadvanced',
                columnsResize: true,
                rendergridrows: function (params) {
                            return params.data;
                        },
                        ready: function () {
                             $("#jqxgrid_recovery").jqxGrid('hideColumn', 'master_print_id');
                             $("#jqxgrid_recovery").jqxGrid('hideColumn', 'id');
                        },
                rendertoolbar: function (toolbar) {
                    var me = this;
                    var container = $("<div style='margin: 5px;'></div>");
                    toolbar.append(container);
                      //LAY MA CHO TRUONG COMBOBOX (MA VAT TU HANG HOA////
                        $("#jqxgrid_recovery").on('cellendedit', function (event) {
                                var column = $("#jqxgrid_recovery").jqxGrid('getcolumn', event.args.datafield);
                        }); 
                        $("#jqxgrid_recovery").on('cellselect', function (event) {
                            var column = $("#jqxgrid_recovery").jqxGrid('getcolumn', event.args.datafield);
                            var value = $("#jqxgrid_recovery").jqxGrid('getcellvalue', event.args.rowindex, column.datafield);
                            var displayValue = $("#jqxgrid_recovery").jqxGrid('getcellvalue', event.args.rowindex, column.displayfield);
                            $("#eventLog").html("<div>Selected Cell<br/>Row: " + event.args.rowindex + ", Column: " + column.text + ", Value: " + value + ", Label: " + displayValue + "</div>");
                        });
                },
                columns: [
                              { text: 'Mã cấp phát',editable: false, dataField: 'master_print_id', width: '25%' }, 
                              { text: 'Tên ấn chỉ',editable: false, dataField: 'name_print', width: '50%' }, 
                                {
                                    text: 'Chọn serial', columntype: 'custom', datafield: 'serial',
                                    createeditor: createGridEditor, initeditor: initGridEditor, geteditorvalue: gridEditorValue
                                }
                          ]
            }); 
           
    }
</script>
    
    