<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">TỔNG HỢP KẾT QUẢ KIỂM TRA,XỬ LÝ</h3>
    </div>    
</div>
<div class="row">
   <div class="panel panel-default">
       <div class="panel-body">
           <div class="form-group">action="<?php echo $this->baseUrl()?>/admin/report/exportalldocviolationshandling"
               <form role="form" method="POST" name="Search" >

                   <!--<div  class="col-lg-1">
                       <label  >Quý</label>
                   </div>
                   <div  class="col-lg-2">
                       <div  id="quy" name="quy">
                       </div>
                   </div>-->

                   <div  class="col-lg-1">
                       <label >Năm</label>
                   </div>
                   <div class="col-lg-2">
                       <div  id="year" name="year">

                       </div>
                   </div>
                   <div class="form-group">
                       <button type="submit" class="btn btn-primary">Xuất Excel</button>
                   </div>

               </form>
           </div>
       </div>
   </div>
</div>
<script type="text/javascript">   
     $(document).ready(function () {
        var y = new Date();
        var i = y.getFullYear();
        /*var arrayquy=new Array();
                        for(var m=1;m<=4;m++){
                       arrayquy[m]=m;
                        }*/
        var arrayyear=new Array();
                        for(var j=i-10;j<=i+10;j++){
                            arrayyear[j]=j;
                        }
 
          //$("#quy").jqxComboBox({ source: arrayquy,selectedIndex:0, width: '100px', height: '25px'});
               
          $("#year").jqxComboBox({ source: arrayyear,selectedIndex:10, width: '100px', height: '25px'});                
    }) ;                   
</script>
 <script type="text/javascript">
     function checkinput(){
                  //  var month = $('#month').val();
                  var frm = window.document.Search;
                 bootbox.alert( $("#year").val());
                 return false;
                }
 </script>

