<?php $identity = Zend_Auth::getInstance()->getIdentity();
               if(!empty($identity)){
//                    $this->model->setSys_Department_Id($identity->sys_department_id);
//                    $this->model->setSys_User_Id($identity->id);
                }
?>

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Đặt lịch</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>   
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" name="AddSchedule" onsubmit="return checkinput()">   
                    <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Tên lịch</label>
                                </div>
                                <div class="col-lg-2">                                                                                
                                    <input type="text" class="form-control" name="name_schedule" id="name_schedule" value="<?php echo $this->item->getName_Schedule(); ?>"> 
                                </div>
                            </div>
                        </div> 
                    <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Tỉnh thành</label>
                                </div>
                                <div class="col-lg-2">                                                                                
                                       <?php echo $this->provinceHTML;?>   
                                </div>
                            </div>
                        </div> 
                    <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Quận huyện</label>
                                </div>
                                <div class="col-lg-2">                                                                                
                                    <?php echo $this->districtHTML;?>
                                    <input type="hidden" name="district_id" id="district_id" value="">
                                </div> 
                            </div>
                        </div> 
                    <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Xã phường</label>
                                </div>
                                <div class="col-lg-2">                                                                                
                                    <?php echo $this->wardHTML;?>
                                     <input type="hidden" name="ward_id" id="ward_id" value="">
                                </div>
                                
                            </div>
                        </div> 
                     <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Từ ngày</label>
                                </div>
                                <div class="col-lg-3" >
                                    <div id='jqxWidget'>
                                        <div id='selection'></div>
                                    </div>
                                    <input type="hidden" name="date_from" id="date_from" value="">
                                </div>
                                <div class="col-lg-1">
                                    <label>Đến ngày</label>
                                </div>
                                 <div class="col-lg-2" >
                                    <div id='jqxWidget1'>
                                        <div id='selection'></div>
                                    </div>
                                    <input type="hidden" name="date_to" id="date_to" value="">
                                </div>
                               
                            </div>
                     </div> 
                      <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Đội thực hiện</label>
                                </div>
                              <div class="col-lg-3">
                                        
                                            <div id="dropDownButton">
                                                <div style="border: none;" id="jqxTree">
                                                    <ul>
                                                   <?php echo GlobalLib::returntree($identity->sys_department_id) ;?>
                                                      
                                                    </ul>
                                                </div>
                                            </div>
                                      
                                          <input class="form-control" type="hidden" name="sys_department_id" id="sys_department_id" value="<?php echo $this->item->getSys_Department_Id(); ?>">
                                    </div> 
<!--                                <div class="col-lg-1">
                                    <input type="checkbox" name="status" id="status" value="1" 
                                        <?php echo ($this->item->getStatus() == 1 ? "checked=\"checked\"" : "") ?> >
                                    
                                </div>
                                <div class="col-lg-2">
                                    <label>Tất cả các đội</label>
                                </div>-->
                                
                               
                            </div>
                        </div> 
                     <div class="form-group">
                                <div class="row">
                                <div class="col-lg-2">
                                    <label>Ghi chú</label>
                                </div>
                               <div class="col-lg-6">
                                    <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="5"><?php echo $this->item->getComment(); ?></textarea>    
                                </div> 
                                </div>
                      </div>
                       <div class="form-group">
                                <button type="submit" name="import" id="import" class="btn btn-primary">Thêm mới</button>
                                <button type="reset" class="btn btn-default">Đặt lại</button>
                                <!--<button type="button" id="bt" class="btn btn-default">Đặt lại12</button>-->
                       </div> 
                    
                </form>
            </div>
        </div>
    </div>
</div>

<script>
    $('#import').on('click',function(){
        $('#ward_id').val($('#master_ward_id').val());
    });
    $('#bt').on('click',function(){
       alert($('#sys_department_id').val()) ;
    });
</script>
<script type="text/javascript">
      $(document).ready(function () {
            $("#dropDownButton").jqxDropDownButton({ width: 150, height: 25,theme: 'bootstrap'});
            $('#jqxTree').on('select', function (event) {
                var args = event.args;
                var item = $('#jqxTree').jqxTree('getItem', args.element);
                var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + item.label + '</div>';
                $("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
                 $("#sys_department_id").val(event.args.element.id);
             $("#jqxTree").jqxTree({disabled:true});
            });
            $("#jqxTree").jqxTree({ width: 200, height: 220,theme: 'bootstrap'});
            
        
    
      $('#master_province_id').multiselect({
            maxHeight: '300',
            enableFiltering: true,
            maxHeight: '300',
            onChange: function(option, checked) {
                if (checked) {
                    orderCount++;
                    $(option).data('order', orderCount);
                }
                else {
                    $(option).data('order', '');
                }
            },
        });
         $('#master_district_id,#master_ward_id').multiselect({
                    includeSelectAllOption:true,
                    enableFiltering: true,
                    maxHeight: '300',
                    buttonText: function(options) 
                    {
                        var retStr = "";
                        if (options.length === 0) {
                           retStr = "Chưa chọn";
                        } else if(options.length <=2){
                           var textArray = [];
                           $.each(options,function(key,value){
                               textArray.push($.trim($(value).html()));
                           });
                           retStr = "<div class='pull-left restricted'>"+textArray.join(",")+"</div>";
                        } else {
                           retStr = options.length+" selected";
                        }
//                        $('#district_id').val($('#master_district_id').val());
//                        $('#ward_id').val($('#master_ward_id').val());
                        return retStr+" <b class='caret'></b>";
                    }  
                });
        $('#jqxWidget,#jqxWidget1').jqxDateTimeInput({ formatString: "dd-MM-yyyy"});
        var formatString = $('#jqxWidget,jqxWidget1').jqxDateTimeInput('formatString');
        $('#jqxWidget').on('valueChanged', function (event) {
                    var date = event.args.date;
                    var text= $('#jqxWidget').jqxDateTimeInput('getText'); 
                     $('#date_from').val(text);
                });
        $('#jqxWidget1').on('valueChanged', function (event) {
                    var date = event.args.date;
                    var text= $('#jqxWidget1').jqxDateTimeInput('getText'); 
                     $('#date_to').val(text);
                });        
                 
               
     });
</script>
<script type="text/javascript">
    document.forms['AddSchedule'].name_schedule.focus();
    function set_focus() {
        document.forms['AddSchedule'].name_schedule.focus();
    }
    function parseDate(str) {
            var mdy = str.split('-');
            return new Date(mdy[2], mdy[1], mdy[0]);
        }
    function checkinput() {
       
        var frm = window.document.AddSchedule;
        if (frm.name_schedule.value == "") {
            bootbox.alert("Vui lòng nhập tên lịch");
            return false;
        };
        if(isNaN(frm.name_schedule.value)== false){
            bootbox.alert("Vui lòng nhập tên lịch bằng chữ");
            return false;
        } 
        if($('#master_province_id').val()==0){
             bootbox.alert("Vui lòng chọn tỉnh thành");
            return false;
        }
        if($('#district_id').val()==""){
             bootbox.alert("Vui lòng chọn quận huyện");
            return false;
        }
        if($('#ward_id').val()==""){
             bootbox.alert("Vui lòng chọn xã phường");
            return false;
        }
        if ($('#jqxWidget').val() == "") {
            bootbox.alert("Vui lòng nhập giá trị ngày bắt đầu");
            return false;
        };
        var stringstartDate =$('#jqxWidget').val()
        if ($('#jqxWidget1').val() == "") {
            bootbox.alert("Vui lòng nhập giá trị ngày kết thúc");
            return false;
        }; 
         var stringendDate =$('#jqxWidget1').val();
            
        var startDate = parseDate(stringstartDate).getTime();
        var endDate = parseDate(stringendDate).getTime();
        if (startDate > endDate){
            bootbox.alert("Vui lòng nhập lại giá trị ngày kết thúc. Ngày kết thúc phải lớn (hoặc bằng) ngày bắt đầu!");
            return false;
        }
       if (($('#sys_department_id').val() == "")) {
            bootbox.alert("Vui chọn đội thực hiện");
            return false;
        }; 
      return true;
    }
</script>