<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">TỔNG HỢP KẾT QUẢ KIỂM TRA,XỬ LÝ</h3>
    </div>    
</div>
<div class="row">
   
   <div class="panel panel-default">
       <div class="panel-body">
           <div class="form-group">
               <form role="form" method="POST" name="Search" action="<?php echo $this->baseUrl()?>/default/report/exportalldocviolationshandling">
                   <div  class="col-lg-1">
                       <label style="margin-left: 20px;" >Năm</label>
                   </div>
                   <div class="col-lg-2">
                       <div style="float: left" id="year" name="year">

                       </div>
                   </div>
                   <div class="form-group">
                       <button type="submit" class="btn btn-primary">Xuất Excel</button>
                   </div>

               </form>
           </div>
       </div>
   </div>
</div>
<script type="text/javascript">   
     $(document).ready(function () {
        var y = new Date();
        var i = y.getFullYear();

        var arrayyear=new Array();
                        for(var j=i-10;j<=i+10;j++){
                            arrayyear[j]=j;
                        }

               
          $("#year").jqxComboBox({ source: arrayyear,selectedIndex:10, width: '100px', height: '25px'});                
    }) ;                   
</script>
 <script type="text/javascript">
     function checkinput(){
                  //  var month = $('#month').val();
                  var frm = window.document.Search;
                 bootbox.alert( $("#year").val());
                 return false;
                }
 </script>

