<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Nhập mới ấn chỉ</h3>
    </div>    
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <form  method="POST" name="Adddocprintcreate">  
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Mã ấn chỉ(*)</label>
                                    </div>
                                    <div class="col-lg-3">
                                       <?php echo GlobalLib::getComboSeclectTitle('master_print_id','master_print', 'id','code', $this->item->getMaster_Print_Id(),'name') ?>
                                    </div>
                                    <div class="col-lg-2">
                                        <label>Ngày nhận(*)</label>
                                    </div>
                                    <div class="col-lg-3">
                                       <div id='jqxWidget'>
                                            <div style='float: left;'>
                                                <div style='float: left; margin-top: 3px;' id='jqxDateTimeInput'>
                                                </div>
                                                <div style='margin-left: 20px; float: left;'>
                                                    <div>
                                                        <input type="hidden" id="ngaycapphat" name="ngaycapphat">
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Đã tạo tới quyển</label>
                                    </div>    
                                    <div class="col-lg-3">
                                        <input class="form-control" name="serial_danhap" id="serial_danhap" value="" readonly="true">
                                          <input type="hidden"  name="name_print" id="name_print" value="" >
                                    </div>
                                    
                                    <div class="col-lg-2">
                                        <label>Số HĐ mua ấn chỉ(*)</label>
                                    </div>
                                    <div class="col-lg-3">
                                        <input class="form-control" name="invoice_number" id="invoice_number" value="<?php echo $this->item->getInvoice_Number(); ?>" placeholder="nhập vào số hóa đơn mua ấn chỉ">
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Quyển số(*)</label>
                                    </div>
                                    <div class="col-lg-3">
                                        <input class="form-control" name="coefficient" id="coefficient" value="<?php echo $this->item->getCoefficient(); ?>" placeholder="1,2,3,...">
                                    </div>
                                   <div class="col-lg-2">
                                        <label>Serial theo quyển(*)</label>
                                       
                                    </div>
                                    <div class="col-lg-3">
                                        <input class="form-control" name="serial" id="serial" placeholder="Quyển: (1-10,11-20,21-30,...)" value="<?php echo $this->item->getSerial(); ?>">
                                        
                                    </div>
                                    <div class="col-lg-2">
                                       
                                        <input class="form-control" name="serial1" id="serial1" placeholder="Serial đã nhập" readonly="true"/>
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-lg-2">
                                    <label>Ghi chú</label>
                                </div> 
                                    <div class="col-lg-10">
                                        <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="3"><?php echo $this->item->getComment(); ?></textarea>    
                                    </div>  
                                </div>                                
                            </div>
                            <input id="selectionlog" style="display: none" name="selectionlog" /> 
                             <div class="row">
                                <div class="col-lg-6">                      
                                        <div class="form-group">
                                            <div class="row">
                                                 <div class="col-lg-9">
                                                     <button type="button" name="add" id="add" class="btn btn-primary" >Thêm</button>
                                                     <input type="button" value="Xóa" id="xoa" class="btn btn-danger icon-trash" />
                                                    <button type="submit" name="luu" id="luu" class="btn btn-primary">Lưu</button>
                                                 </div>   
                                            </div>
                                        </div> 
                                </div>
                             </div>
                        </form>
                    </div>
                </div>
                 <div class="row">
                     <div class="col-lg-12">
                         <!--<div class="panel-body">-->
                            <div class="table-reponsive">
                                <div id="jqxgrid">
                                </div>
                                <div class="row">
                                </div>
                            </div>
                     </div>
                 </div>    
            </div>
        </div>
    </div>   
</div>
<style>
    #t{text-align: right};
</style>
<script type="text/javascript">
        $(document).ready(function () {
             var source =
            {
                datatype: "json",
                datafields:
                [
                    { name: 'master_print_id',type:'int'},
                    { name: 'name_print', type: 'string' }, 
                    { name: 'coefficient', type:'string'},
                    { name: 'serial', type: 'string' },
                    { name: 'invoice_number', type: 'string' },
                    { name: 'created_date', type: 'string' },
                    { name: 'comment', type: 'string' },
                    { name: 'chon', type: 'int' }
                ],
                addrow: function (rowid, rowdata, position, commit) {
                    commit(true);
                },
                deleterow: function (rowid, commit) {
                    commit(true);
                },
                updaterow: function (rowid, newdata, commit) {                   
                    commit(true);
                },
                url:"<?php // echo $this->baseUrl().'/default/docprintallocation/service'?>",
                sortcolumn: 'order',
                sortdirection: 'asc'
            };
            var dataAdapter = new $.jqx.dataAdapter(source, {
                loadComplete: function () {
                }
            });
             $("#jqxgrid").jqxGrid(
            {
                width: '100%',
                height: 350,
                source: dataAdapter,
                showtoolbar: true,
                theme: 'bootstrap',
                pageable: false,
                showfilterrow: true,
                filterable: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                editable: true,
                selectionmode: 'singlerow',
                columnsResize: true,
                rendergridrows: function (params) {
                            return params.data;
                        },
                        ready: function () {
                            $("#jqxgrid").jqxGrid('hideColumn', 'Id');
                             $("#jqxgrid").jqxGrid('hideColumn', 'master_print_id');
                        },
                rendertoolbar: function (toolbar) {
                    var me = this;
                    var container = $("<div style='margin: 0px;'></div>");
                    toolbar.append(container);
                     container.append('<center><div id="t"></div></center>');                    
                    $("#xoa").on('click', function () {
                        var selectedrowindex = $("#jqxgrid").jqxGrid('getselectedrowindex');
                        var rowscount = $("#jqxgrid").jqxGrid('getdatainformation').rowscount;
                        if (selectedrowindex >= 0 && selectedrowindex < rowscount) {
                            var id = $("#jqxgrid").jqxGrid('getrowid', selectedrowindex);
                            var commit = $("#jqxgrid").jqxGrid('deleterow', id);
                        }
                        for (var i = 0; i <= rowscount-1; i++) {
                            var row = $('#jqxgrid').jqxGrid('getRowData', i); 
                            if(row.chon==1){
                                alert(row.chon);
                                var id = $("#jqxgrid").jqxGrid('getrowid', i);
                                var commit = $("#jqxgrid").jqxGrid('deleterow', id);
                            }
                        }
                    });
                    $("#add").on('click', function () {
                    if(checkinput()){
                        $("#luu").show();
                        var flag =0;
                        var id = $("#jqxgrid").jqxGrid('getrowid', 0); 
                        var rowscount = $("#jqxgrid").jqxGrid('getdatainformation').rowscount; 
                        if(rowscount == 0){
                            var datarow = {};
                            datarow["master_print_id"] =$('#master_print_id').val() ;
                            datarow["name_print"] = $('#name_print').val();
                            datarow["coefficient"] = $('#coefficient').val();
                            datarow["serial"] = $('#serial').val();
                            datarow["invoice_number"] = $('#invoice_number').val();
                            datarow["created_date"] = $('#jqxDateTimeInput').val();
                            datarow["comment"] = $('#comment').val();
                            var commit = $("#jqxgrid").jqxGrid('addrow', null, datarow);
                        }else{
                             //kiem tra ma an chi khong dc trung trong bang luu tam
                            for (var i = id; i <= rowscount-1; i++) {
                                var row = $('#jqxgrid').jqxGrid('getRowData', i); 
                                if($('#master_print_id').val() == row.master_print_id){
                                    flag = 1;break;
                                }
                            }
                            if(flag == 0){
                                var datarow = {};
                                datarow["master_print_id"] =$('#master_print_id').val();
                                datarow["name_print"] = $('#name_print').val();
                                datarow["coefficient"] = $('#coefficient').val();
                                datarow["serial"] = $('#serial').val();
                                datarow["invoice_number"] = $('#invoice_number').val();
                                datarow["created_date"] = $('#jqxDateTimeInput').val();
                                datarow["comment"] = $('#comment').val();
                                var commit = $("#jqxgrid").jqxGrid('addrow', null, datarow);
                            }else{
                                bootbox.alert("Không được nhập trùng ấn chỉ trong một lần nhập. Vui lòng kiểm tra và nhập lại");
                            }
                        }
                    }
                });
                    //Thu hồi
                    $("#luu").on('click', function () { 
                        $("#luu").hide();
                        $('#ngaycapphat').val($('#jqxDateTimeInput').val());
                        var id = $("#jqxgrid").jqxGrid('getrowid', 0); 
                        var rowscount = $("#jqxgrid").jqxGrid('getdatainformation').rowscount; 
                        var doc_print_create = new Array();
                        for (var i = id; i <= rowscount-1; i++) {
                            var row = $('#jqxgrid').jqxGrid('getRowData', i); 
                            var date = '"'+row.created_date.toString()+'"';
                               doc_print_create[i] = { invoice_number:row.invoice_number , master_print_id: row.master_print_id,coefficient:row.coefficient,serial:row.serial,created_date:row.created_date};
                        }
                        $.ajax({
                                    type:'post',
                                    url:'<?php echo $this->baseUrl()?>/default/docprintcreate/savedocprintcreate',
                                    data:{'data':doc_print_create},
                                    async:false,
                                    dataType:'json',
                                    success:function(data){
                                    }
                        });
                        for (var i = 0; i <= rowscount-1; i++) {
                                var commit = $("#jqxgrid").jqxGrid('deleterow', i);
                          
                        }
                        ///
                        $('#master_print_id').prop('selecteđInex','0');
                        $('#name_print').val("");
                        $('#coefficient').val("");
                        $('#serial').val("");
                        $('#invoice_number').val();
                        $('#comment').val("");
                        
                    });
                },
                columns: [
                              { text: 'Mã Ấn chỉ ',editable: false, dataField: 'Id', width: '0' },
                              { text: 'mã ấn chỉ',editable: false, dataField: 'master_print_id', width: '10%' }, 
                              { text: 'Tên ấn chỉ',editable: false, dataField: 'name_print', width: '25%' }, 
                              { text: 'Số quyển',editable: false, dataField: 'coefficient', width: '15%' },
                              { text: 'Số serial', editable: true, dataField: 'serial', width: '20%'},
                              { text: 'Số biên lai', editable: true, dataField: 'invoice_number', width: '10%'},
                              { text: 'Ngày nhập', editable: true, dataField: 'created_date', width: '10%'},
                              { text: 'Ghi chú', editable: true, dataField: 'comment', width: '15%'},
                               {text: '  ',filtertype: 'none', cellsalign: 'right', align: "center", columntype: 'checkbox', editable: true, sortable: false, dataField: 'chon', cellsrenderer: function (row) {
                         
                      }
              }
            ]
            });  
        });
    </script>
 <script type="text/javascript">
        $(document).ready(function () {
            var orderCount = 0;
            $("#luu").hide();
             $('#master_print_id').multiselect({
                maxHeight: '300',
                enableFiltering: true,
                maxHeight: '300',
                onChange: function(option, checked) {
                    if (checked) {
                        orderCount++;
                        $(option).data('order', orderCount);
                    }
                    else {
                        $(option).data('order', '');
                    }
                }
            });
        
        $('#master_print_id').on('change', function() {
            var selected = [];
            $('#master_print_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
            $('#jqxDateTimeInput').jqxDateTimeInput({ formatString: "dd-MM-yyyy"});
            var formatString = $('#jqxDateTimeInput').jqxDateTimeInput('formatString');
            $('#jqxDateTimeInput').on('valueChanged', function (event) {
                var date = event.args.date;
                var text= $('#jqxDateTimeInput').jqxDateTimeInput('getText'); 
                 $('#ngaycapphat').val(text);
            });
            $('#jqxDateTimeInput').on('open', function (event) {
                var date = event.args.date;
            });
            $('#jqxDateTimeInput').on('close', function (event) {
                var date = event.args.date;
            });
            //
           
        });
    </script>
<script type="text/javascript">
    document.forms['Adddocprintcreate'].code.focus();
    function set_focus() {
        document.forms['Adddocprintcreate'].code.focus();
    }
   
    function checkinput() {
        var frm = window.document.Adddocprintcreate;
        if($("#master_print_id").val()=="0"){
            bootbox.alert("Vui lòng chọn tên ấn chỉ");
            return false;
        }
        if (frm.coefficient.value == "") {
            bootbox.alert("Vui lòng nhập quyển số");
            return false;
        };
        if (frm.serial.value == "") {
            bootbox.alert("Vui lòng nhập mã serial");
            return false;
        };
         if (frm.invoice_number.value == "") {
            bootbox.alert("Vui lòng nhập số hóa đơn");
            return false;
        };
        var id_master_print="";
        var coefficient="";
         id_master_print = $('#master_print_id').val();
         coefficient= $('#coefficient').val();
        var flag;var value;
        $.ajax({
            type:'post',
            url:'<?php echo $this->baseUrl()?>/default/docprintcreate/checkcoefficient/master_print_id/'+id_master_print+'/coefficient/'+coefficient,
            async:false,
            dataType:'json',
            success:function(data){
                if(data[0].code==1){
                    flag=false;value = data[0].error;
                } else {
                    flag=true;
                }
            }
        });
        if(flag==false){
            var string_error_ttai="";
            var string_error_ttu="";
            var string_error_ktu="";
            for(var i =0; i<value.length;i++ ){
                var error = value[i];
                var list_error = error.split(/;/);
                //tao mang cac phan tu Quyen so da ton tai
                if(list_error[0]=="ttai"){
                    string_error_ttai = string_error_ttai +list_error[1]+',' ;
                }else if(list_error[0]=="ttu"){
                     string_error_ttu = string_error_ttu +list_error[1]+',' ;
                }else{
                     string_error_ktu = string_error_ktu +list_error[1]+',' ;
                }
            }
            if(string_error_ttai !=""){
                bootbox.alert("Quyển số:( "+string_error_ttai+") đã tồn tại. Vui lòng kiểm tra và nhập lại.");
            }
            if(string_error_ttu !=""){
                bootbox.alert("Quyển số này được tạo không đúng thứ tự( "+string_error_ttu+"). Vui lòng kiểm tra và nhập lại.");
            }
            if(string_error_ktu !=""){
                 bootbox.alert("Không được nhập ký tự("+string_error_ktu+") cho số quyển. Vui lòng kiểm tra và nhập lại.");
             }
            return false;
        };
        var serial="";
            serial= $('#serial').val();
        var flags;var values;
        $.ajax({
            type:'post',
            url:'<?php echo $this->baseUrl()?>/default/docprintcreate/checkserialnew/serial/'+serial+'/id_master_print/'+id_master_print+'/coefficient/'+coefficient,
            async:false,
            dataType:'json',
            success:function(data){
                if(data[0].code==1){
                    flags=false;values = data[0].error;
                } else {
                    flags=true;
                }
            }
        });
         if(flags==false){
            var string_error_ttais="";
            var string_error_kdc_tao="";
            var string_error_ktus="";
            var string_error_thieu="";
            for(var i =0; i<values.length;i++ ){
                var error = values[i];
                var list_error = error.split(/;/);
                //tao mang cac phan tu Quyen so da ton tai
                if(list_error[0]=="ttai"){
                    string_error_ttais = string_error_ttais +list_error[1]+',' ;
                }else if(list_error[0]=="kdc_tao"){
                     string_error_kdc_tao = string_error_kdc_tao +list_error[1]+',' ;
                }else if(list_error[0]=="ktu"){
                     string_error_ktus = string_error_ktus +list_error[1]+',' ;
                }else{
                    string_error_thieu = string_error_thieu +list_error[1]+',' ;
                }
            }
            if(string_error_ttais !=""){
                bootbox.alert("Dãy serial này:( "+string_error_ttais+") đã tồn tại. Vui lòng kiểm tra và nhập lại.");
            }
            if(string_error_kdc_tao !=""){
                bootbox.alert("Dãy serial này không đúng( "+string_error_kdc_tao+"). Vui lòng kiểm tra và nhập lại.");
            }
            if(string_error_ktus !=""){
                 bootbox.alert("Không được nhập ký tự("+string_error_ktus+") cho serial. Vui lòng kiểm tra và nhập lại.");
             }
             if(string_error_thieu !=""){
                 bootbox.alert("Nhập serial bị thiếu . Vui lòng kiểm tra và nhập lại.");
             }
            return false;
        };
      return true;
    }
</script>
<script>
    $("#master_print_id").on('change',function(data){
        var serial_danhap;
        var masterprintid = $("#master_print_id").val();
        $.ajax({
            type:'post',
            url:'<?php echo $this->baseUrl()?>/default/docprintcreate/coefficientdaco/id_master_print/'+masterprintid,
            async:false,
            dataType:'json',
            success:function(data){
                if(data[0].coefficientdanhap == null){
                    serial_danhap = "Chưa tạo quyển nào";$('#name_print').val(data[0].name_print);$('#serial1').val("chưa có");
                }else{
                    serial_danhap ="Quyển số: "+data[0].coefficientdanhap; $('#name_print').val(data[0].name_print);$('#serial1').val(data[0].serial);
                    
                }
            }
        });       
       // alert(serial_danhap);
       $("#serial_danhap").val(serial_danhap); 
       //$("#serial1").val("chưa có");
    });
</script>