<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->

<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Thêm đặc quyền</h3>
    </div>
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-8">
                        <form role="form" method="POST" name="AddSysPrivileges" onsubmit="return checkinput();">
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Tên đặc quyền</label>
                                    </div>
                                    <div class="col-lg-6">                                                                     
                                        <input class="form-control" name="name" id="name" value="<?php echo $this->item->getName() ?>">                                        
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Module</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control"type="module" name="module" id="module" value="<?php echo $this->item->getModule() ?>">
                                    </div>
                                    
                                </div>
                            </div>  
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Controller</label>
                                    </div>
                                    <div class="col-lg-6">                                                                     
                                        <input class="form-control" name="controller" id="controller" value="<?php echo $this->item->getController() ?>">                                        
                                    </div>
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Action</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control" name="action" id="action" type="action" value="<?php echo $this->item->getAction() ?>">
                                    </div>
                                    
                                </div>
                            </div>       
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Thứ tự</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control" name="order" id="order" value="<?php echo $this->item->getOrder() ?>">
                                    </div>
                                    
                                </div>
                            </div>
                             <div class="form-group">
                                <div class="row">
                                <div class="col-lg-3">
                                    <label>Hiển thị</label>
                                </div>
                                <div class="col-lg-6">
                                    <input type="checkbox" name="status" id="status" value="1" 
                                        <?php echo ($this->item->getStatus() == 1 ? "checked=\"checked\"" : "") ?> >
                                </div>
                                </div>
                            </div>
                             <div class="form-group">
                                <div class="row">
                                <div class="col-lg-3">
                                    <label>Ghi chú</label>
                                </div> 
                                    <div class="col-lg-6">
                                        <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="5"><?php echo $this->item->getComment(); ?></textarea>    
                                    </div>  
                                </div>                                
                             </div>
                            <input id="selectionlog" style="display: none" name="selectionlog" />              
                            <center><div class="form-group">
                                <button type="submit" class="btn btn-primary">Thêm mới</button>
                                <button type="reset" class="btn btn-default">Đặt lại</button>
                                </div></center>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>
<script type="text/javascript">
            // When the document is ready
            $(document).ready(function () {
                
                $('#birthday').datepicker({
                    dateFormat: "dd-mm-yy"
                });  
            
            });
</script>
<script type="text/javascript">
    document.forms['AddSysPrivileges'].name.focus();
    function set_focus() {
        document.forms['AddSysPrivileges'].name.focus();
    }
    function checkinput() {        
        var frm = window.document.AddSysPrivileges;
        if (frm.name.value == "") {
            bootbox.alert("Vui lòng nhập đầy đủ tên");
            return false;
        }
        if (frm.module.value == "") {
            bootbox.alert("Vui lòng nhập module");
            return false;
        }
        if (frm.controller.value == "") {
            bootbox.alert("Vui lòng nhập controller");
            return false;
        }
        if (frm.action.value == "") {
            bootbox.alert("Vui lòng nhập action");
            return false;
        }       
        
        return true;
    }
</script>
<script type="text/javascript">
     $(document).ready(function() {       
        $('#sys_department_id').multiselect({
            maxHeight: '300',
            enableFiltering: true,
            maxHeight: '300',
            onChange: function(option, checked) {
                if (checked) {
                    orderCount++;
                    $(option).data('order', orderCount);
                }
                else {
                    $(option).data('order', '');
                }
            },
        });
        
        $('#sys_department_id').on('change', function() {
            var selected = [];
            $('#sys_department_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
         $('#sys_user_group_id').multiselect({
            maxHeight: '300',
            enableFiltering: true,
            maxHeight: '300',
            onChange: function(option, checked) {
                if (checked) {
                    orderCount++;
                    $(option).data('order', orderCount);
                }
                else {
                    $(option).data('order', '');
                }
            },
        });
        
        $('#sys_user_group_id').on('change', function() {
            var selected = [];
            $('#sys_user_group_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
    });
</script>