<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Thêm nhóm người dùng chi tiết</h3>
    </div>   
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-6">
                        <form role="form" method="POST" name="AddUserGroupDetail" onsubmit="return checkinput(); ">                                    
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Tên nhóm người dùng</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <?php echo GlobalLib::getCombo('sys_user_group_id', 'sys_user_group', 'id', 'group_name', $this->item->getSys_User_Group_Id()) ?>   
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Đặc quyền</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <?php echo GlobalLib::getCombo('sys_privileges_id', 'sys_privileges', 'id', 'name', $this->item->getSys_Privileges()) ?>   
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Thứ tự</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control" name="order" id="order" value="<?php echo $this->item->getOrder(); ?>">
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                <div class="col-lg-3">
                                    <label>Trạng thái</label>
                                </div>
                                <div class="col-lg-6">
                                    <input class="form-control" name="status" id="status" value="<?php echo $this->item->getStatus(); ?>">
                                </div>
                                </div>
                            </div>
                             <div class="form-group">
                                <div class="row">
                                <div class="col-lg-3">
                                    <label>Ghi chú</label>
                                </div> 
                                    <div class="col-lg-6">
                                        <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="5"><?php echo $this->item->getComment(); ?></textarea>    
                                    </div>  
                                </div>
                                
                             </div>
<!--                            <div class="form-group">
                                <div class="row">
                                <div class="col-lg-3">
                                    <label>Hiển thị</label>
                                </div>
                                <div class="col-lg-6">
                                    <input type="checkbox" name="status_province" id="status_province" value="1" 
                                        <?php //echo ($this->item->getStatus() == 1 ? "checked=\"checked\"" : "") ?> >
                                </div>
                                </div>
                            </div>                          -->
                                        
                             <input id="selectionlog" style="display: none" name="selectionlog" />            
                            <div class="form-group">
                                <center>
                                <div class="row">
                                <button type="submit" name="addusergroupdetial" id="addusergroupdetial" class="btn btn-primary">Lưu</button>
                                <button type="reset" class="btn btn-default">Đặt lại</button> </                              
                                </div> </center>   
                                
                            </div> 
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>

<script type="text/javascript">
    document.forms['AddUserGroupDetail'].name.focus();
    function set_focus() {
        document.forms['AddUserGroupDetail'].name.focus();
    }   
    function checkinput() {
        var frm = window.document.AddUserGroupDetail;
        if($('#sys_user_group_id').val()=="0"){
            bootbox.alert("Vui lòng chọn nhóm người dùng");
            return false;
        }
        if($('#sys_privileges_id').val()=="0"){
            bootbox.alert("Vui lòng chọn tên quyền");
            return false;
        }
        if(isNaN(frm.status.value)== false){
            bootbox.alert("Vui lòng nhập trạng thái bằng chữ");
            return false;
        } 
        if(frm.status.value == ""){
             bootbox.alert("Vui lòng nhập trạng thái");
            return false;
        }
      return true;
    }
</script>
<script type="text/javascript">
     $(document).ready(function() {       
        $('#sys_user_group_id').multiselect({
            maxHeight: '300',
            enableFiltering: true,
            maxHeight: '300',
            onChange: function(option, checked) {
                if (checked) {
                    orderCount++;
                    $(option).data('order', orderCount);
                }
                else {
                    $(option).data('order', '');
                }
            },
        });
        
        $('#sys_user_group_id').on('change', function() {
            var selected = [];
            $('#sys_user_group_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
         $('#sys_privileges_id').multiselect({
            maxHeight: '300',
            enableFiltering: true,
            maxHeight: '300',
            onChange: function(option, checked) {
                if (checked) {
                    orderCount++;
                    $(option).data('order', orderCount);
                }
                else {
                    $(option).data('order', '');
                }
            },
        });
        
        $('#sys_privileges_id').on('change', function() {
            var selected = [];
            $('#sys_privileges_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
    });
</script>