<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Danh sách tang vật trả lại</h3>
    </div>
</div>

<div class="panel-body">
    <div class="form-group">
        <form role="form" method="POST" name="Search" onsubmit="">
            <div class="row" id="jqxcombobox">
                <div  class="col-lg-1">
                    <label >Tháng</label>
                </div>
                <div  class="col-lg-2">
                    <div  id='month' name='month'>
                    </div>
                </div>

                <div  class="col-lg-1">
                    <label >Năm</label>
                </div>
                <div class="col-lg-2">
                    <div id='year' name='year'></div>
                </div>
                <div class="form-group">
                    <button type="submit" class="btn btn-primary">Tìm</button>
                </div>
            </div>
        </form>
    </div>

    <div class="form-group" >
        <div id="jqxWidget">
            <div id="jqxgrid"></div>
        </div>

        <input style="display: none" id="hide"/>
    </div>
</div>

<div class="col-lg-12">
    <div class="form-group">
        <div class="row">
            <input type="button" value="Xuất Excel" id='excelExport' class="btn btn-primary" />
        </div>
    </div>
</div>

<script type="text/javascript">
        $(document).ready(function () {
             var month = "<?php echo $this->month?>";
             var year = "<?php echo $this->year?>";
             var y = new Date();
             var i = y.getFullYear();
             var arraymonth=new Array();
                        for(var m=1;m<=12;m++){
                       arraymonth[m]=m;
                        }
                function selectedmonth(){
                    if(month == ""){
                        month = y.getMonth()+1;
                        return month;
                    }
                    else return month;
                }
                function selectedyear(){
                if(year==""){
                    year = y.getFullYear();
                  return  10;
                    } 
                else {
                    var selectyear =  year;
                        selectyear = i-selectyear;
                        selectyear = 10-selectyear;
                        return selectyear;
                    }
                }
               
            $("#month").jqxComboBox({ source: arraymonth,selectedIndex:selectedmonth()-1, width: '100px', height: '25px'});
                var arrayyear=new Array();
                        for(var j=i-10;j<=i+10;j++){
                            arrayyear[j]=j;
                        }
            $("#year").jqxComboBox({ source: arrayyear,selectedIndex:selectedyear(), width: '100px', height: '25px'});
            loadgrid("jqxgrid","TL_TG",month,year,"Danh sách tang vật trả lại");
            var _selStatus = "TL_TG";
           
            function loadgrid(_grid,_status,_month,_year,_exel){
            var url = "<?php echo $this->baseUrl()?>/default/docitemshandling/servicetangvattralai/status/"+_status+"/month/"+_month+"/year/"+_year;

            var source =
            {
                dataType: "json",
                dataFields: [
                    { name: 'id', type: 'int' },
                    { name: 'master_items_id', type: 'string' },
                    { name: 'master_sanction_id', type: 'string' },
                    { name: 'info_schedule_check_id', type: 'string' },
                    { name: 'serial_handling', type: 'string' },
                    { name: 'quantity_commodity', type: 'string' },
                    { name: 'master_unit_id', type: 'string' },
                    { name: 'master_unit_name', type: 'string' },
                    { name: 'date_handling', type: 'string' },
                    { name: 'amount', type: 'string' },
                    { name: 'status', type: 'string' },
                    { name: 'comment', type: 'int' } 
                ],
                url:url
            };
            var dataAdapter = new $.jqx.dataAdapter(source);
            $("#excelExport").jqxButton();
            $("#excelExport").click(function () {
                //$("#"+_grid).jqxGrid('exportdata', 'xls', _exel);
                return window.location = "<?php echo $this->baseUrl()?>/default/report/exportdanhsachtangvattralai/status/"+_selStatus+"/month/"+_month+"/year/"+_year;
            });
            $("#"+_grid).jqxGrid(
            {
                width: '100%',
                source: dataAdapter,  
                theme: 'bootstrap',
                pageable: true,
                showfilterrow: true,
                filterable: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                selectionmode: 'multiplecellsadvanced',
                columnsResize: true,
                rendergridrows: function (params) {
                    return params.data;
                },
                ready: function () {
                    $("#"+_grid).jqxGrid('hideColumn', 'id');
                },
                columns: [   
                    { text: 'id', dataField: 'id',align: "center", width: '0%' },
                    {  text: 'Số TT', sortable: false, filterable: false, editable: false,
                     groupable: false, draggable: false, resizable: false,
                     datafield: '', columntype: 'number', width: '5%',
                     cellsrenderer: function (row, column, value) {
                          return "<div style='margin:7px;'>" + (value + 1) + "</div>";
                      }
                    },
                    { text: 'Tên hàng hóa', dataField: 'master_items_id',align: "center", width: '16%' },
                    { text: 'Đối tượng', dataField: 'info_schedule_check_id',align: "center", width: '25%' },
                    { text: 'Biên lai tạm giữ', dataField: 'serial_handling',align: "center", width: '10%' },
                    { text: 'Số lượng', dataField: 'quantity_commodity',align: "center", width: '9%' },
                    { text: 'Đơn vị tính', dataField: 'master_unit_name',align: "center", width: '9%' },
                    { text: 'Ngày trả lại', dataField: 'date_handling',align: "center", width: '10%' },
                    //{ text: 'Số tiền', dataField: 'amount',align: "center", width: '9%' },
                    { text: 'Trạng thái', dataField: 'master_sanction_id',align: "center", width: '16%' },

                ]
              });   
            }
        });
       
    </script>
    <script type="text/javascript">
        function jsdelete(id)
        {
            $.get("<?php echo $this->baseUrl() ?>/default/infoschedule/confirmdelete/id/"+id,null,function(data){
                if(data>0)
                {
                    bootbox.confirm("Hiện có quận huyện thuộc tỉnh thành này và quản trị viên quản lý tỉnh thành này. "
                        +"Bạn có muốn xoá tỉnh thành này và tất cả các quận huyện trực thuộc không?",function(result){
                            if(result == true)
                            {
                                return window.location = "<?php echo $this->baseUrl() ?>/default/province/delete/id/"+id;
                            }
                        });
                    return false;
                }
                else 
                {
                    bootbox.confirm("Bạn có chắc muốn xoá lịch này không?",
                    function(result){
                        if(result == true)
                        {
                           return window.location = "<?php echo $this->baseUrl() ?>/default/infoschedule/delete/id/"+id;
                        }
                    });
                }
            });
        }
    </script>
   