<div class="row">
     <div class="col-lg-12">
        <h3 class="page-header">Danh sách Quy mô Doanh nghiệp/Hộ Kinh Doanh</h3>
    </div>  
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">             
            <div class="panel-heading">
                <div class="row">
                     <div class="col-lg-2" style="text-align:center;width: 9%;padding-right: 0px;">
                         <a  href="<?php echo $this->baseUrl().'/admin/masterbusinesssize/add/'?>">
                             <button type="button" class="btn btn-success btn-action"><i class="fa fa-plus fa-2x"></i>
                             </button></br>
                             <span >Thêm Mới</span>
                         </a>
                     </div>
<!--                     <div class="col-lg-2" style="text-align:center;width: 9%;padding-right: 0px;;padding-left: 1px;">
                         <a  href="<?php // echo $this->baseUrl().'/admin/infobusiness/add/type_business/'.$this->type_business?>">
                            <button type="button" class="btn btn-info btn-action"><i class="fa fa-pencil fa-2x"></i>
                            </button></br>
                             <span >Chỉnh sửa</span>
                         </a>
                     </div>
                      <div class="col-lg-2" style="text-align:center;width: 5%;padding-right: 0px;;padding-left: 1px;">
                         <a  href="<?php // echo $this->baseUrl().'/admin/infobusiness/add/type_business/'.$this->type_business?>">
                            <button type="button" class="btn btn-danger btn-action"><i class="fa fa-minus fa-2x"></i>
                            </button></br>
                             <span >Xóa</span>
                         </a>
                     </div>-->
                     
                 </div>
            </div>
            <div class="panel-body">
                <div class="table-reponsive">
                    <div id="jqxgrid">

                    </div>
                </div>
            </div>
    </div>
</div>
    
<script type="text/javascript">
        $(document).ready(function () {
            // prepare the data
            var source =
            {
                datatype: "json",
                datafields:
                [
                    { name: 'Id',type:'int'},
                    { name: 'code', type: 'string' }, 
                    { name: 'name', type: 'string' },
                    { name: 'comment',type:'string'},
//                    { name: 'status', type:'int'},
//                    { name: 'order', type: 'int' }
                ],
                url:"<?php echo $this->baseUrl().'/admin/masterbusinesssize/service'?>",
                 sortcolumn: 'Id',
               sortdirection: 'DESC'
               
            };
         var dataAdapter = new $.jqx.dataAdapter(source, {
                loadComplete: function () {
                }
            });
            $("#jqxgrid").jqxGrid(
            {
                width: '100%',
                source: dataAdapter,  
                theme: 'bootstrap',
                pageable: true,
                showfilterrow: true,
                filterable: true,
                autoheight: true,
                sortable: true,
                altrows: true,
                enabletooltips: true,
                selectionmode: 'singlerow',
                columnsResize: true,
                rendergridrows: function (params) {
                    return params.data;
                },
                ready: function () {
                    $("#jqxgrid").jqxGrid('hideColumn', 'Id');
                },
                columns: [
                  { text: 'Mã Code',editable: false, dataField: 'code', width: '15%' },
                  { text: 'Tên Loại quy mô',editable: false, dataField: 'name', width: '25%' },                 
                  { text: 'Ghi chú',editable: false, dataField: 'comment', width: '20%' },
//                  { text: 'Thứ tự', editable: false, dataField: 'order', width: '10%' },
                  {text: 'Xóa',filtertype: 'none', cellsalign: 'right', align: "center", columnType: 'none', editable: false, sortable: false, dataField: null, cellsrenderer: function (row) {
                          // render custom column.
                          editrow = row;
                          var dataRecord = $("#jqxgrid").jqxGrid('getrowdata',editrow);
                          var url= "<div style='overflow: hidden; text-overflow: ellipsis; padding-bottom: 2px; text-align: center; margin-right: 2px; margin-left: 4px; margin-top: 4px;'><a class='fa fa-trash-o fa-lg'";
                          url = url + "href='#' onclick='return jsdelete("+dataRecord.Id+")'></a></div>"
                          return url;
                      }
              },
              {text: 'Sửa',filtertype: 'none', cellsalign: 'right', align: "center", columnType: 'none', editable: false, sortable: false, dataField: null, cellsrenderer: function (row) {
                          // render custom column.
                          editrow = row;
                          var dataRecord = $("#jqxgrid").jqxGrid('getrowdata',editrow);
                          var url= "<div style='overflow: hidden; text-overflow: ellipsis; padding-bottom: 2px; text-align: center; margin-right: 2px; margin-left: 4px; margin-top: 4px;'><a class='fa fa-edit fa-lg'";
                          url = url + "href='<?php echo $this->baseUrl() ?>/admin/masterbusinesssize/edit/id/"+dataRecord.Id+"'></a></div>"
                          return url;
                      }
                          }
                ]
            });
           
        });
    </script>
    <script type="text/javascript">
        function jsdelete(id)
        {            
                    bootbox.confirm("Bạn có chắc muốn xoá mặt hàng này không này không?",
                    function(result){
                        if(result == true)
                        {
                           return window.location = "<?php echo $this->baseUrl() ?>/admin/masterbusinesssize/delete/id/"+id;
                        }
                    });             
        }
    </script>