<?php $identity = Zend_Auth::getInstance()->getIdentity();
               if(!empty($identity)){
//                    $this->model->setSys_Department_Id($identity->sys_department_id);
//                    $this->model->setSys_User_Id($identity->id);
                }
?>
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Kiểm tra kinh doanh</h3>
    </div>
    <!-- /.col-lg-12 -->
</div>   
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <form role="form" method="POST" name="AddSchedulecheck" onsubmit="return checkinput();">   
                  <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Phòng ban</label>
                                </div>
                              <div class="col-lg-4">
                                      
                                            <div id="dropDownButton">
                                                <div style="border: none;" id="jqxTree">
                                                    <ul>
                                                   <?php echo GlobalLib::returntree($identity->sys_department_id) ;?>
                                                      
                                                    </ul>
                                                </div>
                                            </div>
                                       
                                          <input class="form-control" type="hidden" name="sys_department_id" id="sys_department_id" value="">
                                    </div>      
                               
                            </div>
                        </div> 
                    <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Kiểm tra theo lịch</label>
                                    </div>
                               <div class="col-lg-4">
                                   <?php echo $this->scheduleHTML; ?>
                                      <?php // echo GlobalLib::getCombo('info_schedule_id', 'info_schedule', 'id', 'name_schedule',$this->item->getInfo_Schedule_Id(), false, 'where sys_department_id=17') ?>                                       
                                  </div>
                                    
                                </div>
                            </div>
                     <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Tên doanh nghiệp</label>
                                    </div>
                                     <div class="col-lg-4">
                                      <?php echo GlobalLib::getCombo('info_business_id', 'info_business', 'id', 'name', $this->item->getInfo_Business_Id(),false,'where created_by ='.$identity->id.'') ?>                                       
                                  </div>
                                </div>
                            </div>
                            <div class="form-group">
                                   <div class="row">
                                       <div class="col-lg-2">
                                           <label>Ấn chỉ</label>
                                       </div>
                                       <div class="col-lg-4">
                                             <?php echo GlobalLib::getCombo('master_print_id', 'master_print', 'id', 'code',0,false, 'where id in(select distinct master_print_id from doc_print_allocation where sys_department_id='.$identity->sys_department_id.' and status ="DOING" and is_delete ="0")', '', 'onchange="getPrintCreatWithMasterPrint1(\'' . $this->aConfig["site"]["url"] . '\')"') ?>                                       
                                         </div>

                                   </div>
                            </div>
                            
<!--                      <div class="form-group">
                            <div class="row">
                                <div class="col-lg-2">
                                    <label>Số cuốn</label>
                                </div>
                            <div class="col-lg-4">
                                 <?php // echo $this->printcreatHTML;?>
                                      <?php // echo GlobalLib::getCombo('doc_print_create_id', 'doc_print_allocation', 'id', 'doc_print_create_id',0,false, 'where master_print_id=0') ?>                                       
                             <input class="form-control" type="hidden" name="doc_print_allocation_id" id="doc_print_allocation_id" value="">      
                            </div>
                            </div>
                        </div> -->
                     <div class="form-group">
                                   <div class="row">
                                       <div class="col-lg-2">
                                          <label>Serial</label>
                                       </div>
                                       <div class="col-lg-4">
                                            <div id="abc"></div> 
                                             <input class="form-control" type="hidden" name="doc_print_allocation_id" id="doc_print_allocation_id" value="">    
                                            <input class="form-control" name="serial_check" id="serial_check" type="hidden">
                                            <input class="form-control" name="serial" id="serial" type="hidden">
                                            <input class="form-control" name="serial1" id="serial1" type="hidden">
                                       </div>
                                   </div>
                            </div>
                            
                    
                      <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Ngày</label>
                                    </div>
                                    <div class="col-lg-7">
                                        <div id="jqxWidget">
                                            <div style="float: left;">
                                                <div style="float: left; margin-top: 3px;" id="jqxDateTimeInput">
                                                </div>
                                            <div style='margin-left: 20px; float: left;'>
                                                <div>
                                                    <input type="hidden" id="date_check" name="date_check" value=" ">
                                                </div>
                                            </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                      
<!--                      <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-2">
                                        <label>Nhân viên</label>
                                    </div>   
                                         <div class="col-lg-4">
                                          <?php echo GlobalLib::getCombo('sys_user_id', 'sys_user', 'id', 'username',  $identity->id,'', 'where sys_department_id=0', '', '') ?>                                       
                             
                                         </div>
                                    
                                </div>
                            </div>-->
                        <div class="form-group">
                                <div class="row">
                                <div class="col-lg-2">
                                    <label>Có vi phạm</label>
                                </div>
                               <div class="col-lg-2">
                                     <input  type="checkbox" name="is_violations" id="is_violations" value="<?php echo $this->item->getIs_Violations();?>">
                                </div> 
                                </div>
                            </div>
                       <div class="form-group">
                                <div class="row">
                                <div class="col-lg-2">
                                    <label>Ghi chú</label>
                                </div>
                               <div class="col-lg-4">
                                    <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="5"><?php echo $this->item->getComment(); ?></textarea>    
                                </div> 
                                </div>
                      </div>
                  
              
                       <input id="selectionlog" style="display: none" name="selectionlog" /> 
                       <div class="form-group">
                           <!--<button type="button" name="bt" id="bt" class="btn btn-primary">Thêm mớifdf</button>-->
                                <button type="submit" name="import" id="import" class="btn btn-primary">Thêm mới</button>
                                <button type="reset" class="btn btn-default">Đặt lại</button>
                       </div> 
                    
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('#bt').on('click',function(){
        alert($('#info_schedule_id').val());
    });
</script>
<script>
    $('#doc_print_create_id').on('change',function(data){
        var doc_print_create_id = $('#doc_print_create_id').val();
        var master_print_id = $('#master_print_id').val();
        $('#serial').val(doc_print_create_id);
        var seriall = $('#serial').val();
        var arrayserial;
        var arrayserialcheck;
        $.ajax({
            type:'post',
            url:'<?php echo $this->baseUrl()?>/default/infoschedulecheck/returnserial/master_print_id/'+master_print_id+'/doc_print_create_id/'+seriall,
            async:false,
            dataType:'json',
            success:function(data){
//                alert(data);
                arrayserial = data[0].serial;
                arrayserialcheck = data[0].serial_check;
            }
        });
        //tao mang
        var array_serial = new Array();var j=0;
        for(var i =0;i<arrayserial.length;i++){
            if(ckeckint(arrayserial[i],arrayserialcheck)!= 1){
                array_serial[j++]=arrayserial[i];
            }
        }
        $('#serial1').val(arrayserial);
        var combobox;
         $.ajax({
            type:'post',
            url:'<?php echo $this->baseUrl()?>/default/infoschedulecheck/combobox',
            data:{'arraycombobox':array_serial},
            async:false,
            dataType:'json',
            success:function(data){
                combobox = data;
            }
        });
        $('#a').show();
        $('#a').html(combobox);
         $('#cobo_id').multiselect({
                maxHeight: '300',
                enableFiltering: true,
                maxHeight: '300',
                onChange: function(option, checked) {
                    if (checked) {
                        orderCount++;
                        $(option).data('order', orderCount);
                    }
                    else {
                        $(option).data('order', '');
                    }
                },
            });
        
        $('#cobo_id').on('change', function() {
            var selected = [];
            $('#cobo_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
    });
</script>

<script type="text/javascript">
      $(document).ready(function () {
           <?php if($identity->is_leader != 1)
              {
                    echo "$('#sys_user_id').attr('disabled', true);";
              }
            ?>
          
            $("#dropDownButton").jqxDropDownButton({ width: 150, height: 25,theme: 'bootstrap'});
            $('#jqxTree').on('select', function (event) {
                var args = event.args;
                var item = $('#jqxTree').jqxTree('getItem', args.element);
                var dropDownContent = '<div style="position: relative; margin-left: 3px; margin-top: 5px;">' + item.label + '</div>';
                $("#dropDownButton").jqxDropDownButton('setContent', dropDownContent);
                $("#sys_department_id").val(event.args.element.id);
                var url = "<?php echo $this->aConfig["site"]["url"]?>";
                
                getMasterPrintWithDepartmentcbd(url+'default/service/index',0,0,0);
               
                //
                 var url = "<?php echo $this->aConfig["site"]["url"]?>";
                var dataarray = new Array();
                    dataarray[0]={master_print_id:$('#master_print_id').val(),sys_department_id:$('#sys_department_id').val(),defaultserial:0};
                var combobox = new Array();
//                $("#jqxTree").jqxTree({disabled:true});
                $.ajax({
                    type:'post',
                    url:'<?php echo $this->baseUrl()?>/default/docviolationshandling/arrayserialcheck',
                    data:{'data':dataarray},
                    async:false,
                    dataType:'json',
                    success:function(data){
                        combobox = data;
                    }
                });
               // alert(combobox);
                $('#abc').html(combobox);
                $('#cobo_id').multiselect({
                       maxHeight: '300',
                       enableFiltering: true,
                       maxHeight: '300',
                       onChange: function(option, checked) {
                           if (checked) {
                               orderCount++;
                               $(option).data('order', orderCount);
                           }
                           else {
                               $(option).data('order', '');
                           }
                       },
                   });

               $('#cobo_id').on('change', function() {
                   var selected = [];
                   $('#cobo_id option:selected').each(function() {
                       selected.push([$(this).val(), $(this).data('order')]);
                   });

                   selected.sort(function(a, b) {
                       return a[1] - b[1];
                   });

                   var text = '';
                   for (var i = 0; i < selected.length; i++) {
                       text += selected[i][0] + ', ';
                   }
                   text = text.substring(0, text.length - 2);

                   $('#selectionlog').val(text);
                   $('#selectionlog').text(text);
               });
                
                 $("#jqxTree").jqxTree({disabled:true});
                 $('#cobo_id').prop('selectedIndex','0');
                
            });
            $("#jqxTree").jqxTree({ width: 200, height: 220,theme: 'bootstrap',disabled:false});
            $('#info_business_id,#master_print_id,#doc_print_create_id,#info_schedule_id,#sys_user_id').multiselect({
            enableFiltering: true,
            maxHeight: '300'
            });
            $('#jqxDateTimeInput').jqxDateTimeInput({ formatString: "dd-MM-yyyy"});
                var formatString = $('#jqxDateTimeInput').jqxDateTimeInput('formatString');
                $('#jqxDateTimeInput').on('valueChanged', function (event) {
                    var date = event.args.date;
                    var text= $('#jqxDateTimeInput').jqxDateTimeInput('getText'); 
                     $('#date_check').val(text);
                });
            $('#doc_print_create_id').on('change', function (event) {
                $('#doc_print_allocation_id').val($('#doc_print_create_id').val());
            });
            
        });
    
</script>
<script>
    $('#import').on('click',function(data){
        $('#date_check').val($('#jqxDateTimeInput').val());
        $('#serial_check').val($('#cobo_id').val());
         $('#doc_print_allocation_id').val($('#cobo_id').val()); 
    });
</script>
<script>
    $('#master_print_id').on('change',function(){
         var dataarray = new Array();var defaultserial;
        
                    dataarray[0]={master_print_id:$('#master_print_id').val(),sys_department_id:$('#sys_department_id').val(),defaultserial:0};
                var combobox = new Array();
                $.ajax({
                    type:'post',
                    url:'<?php echo $this->baseUrl()?>/default/docviolationshandling/arrayserialcheck',
                    data:{'data':dataarray},
                    async:false,
                    dataType:'json',
                    success:function(data){
                        combobox = data;
                    }
                });
//                alert(combobox);
                $('#abc').html(combobox);
                $('#cobo_id').multiselect({
                       maxHeight: '300',
                       enableFiltering: true,
                       maxHeight: '300',
                       onChange: function(option, checked) {
                           if (checked) {
                               orderCount++;
                               $(option).data('order', orderCount);
                           }
                           else {
                               $(option).data('order', '');
                           }
                       },
                   });

               $('#cobo_id').on('change', function() {
                   var selected = [];
                   $('#cobo_id option:selected').each(function() {
                       selected.push([$(this).val(), $(this).data('order')]);
                   });

                   selected.sort(function(a, b) {
                       return a[1] - b[1];
                   });

                   var text = '';
                   for (var i = 0; i < selected.length; i++) {
                       text += selected[i][0] + ', ';
                   }
                   text = text.substring(0, text.length - 2);

                   $('#selectionlog').val(text);
                   $('#selectionlog').text(text);
               });
    });
</script>
<script type="text/javascript">
    document.forms['AddSchedulecheck'].name_schedule.focus();
    function set_focus() {
        document.forms['AddSchedulecheck'].name_schedule.focus();
    }
    function checkinput() {
        var frm = window.document.AddSchedulecheck;
       if (($('#sys_department_id').val() == "")) {
            bootbox.alert("Vui chọn đội thực hiện");
            return false;
        }; 
         if (($('#info_schedule_id').val() == 0)) {
            bootbox.alert("Vui chọn lịch kiểm tra");
            return false;
        }; 
        if (($('#info_business_id').val() == 0)) {
            bootbox.alert("Vui chọn doanh nghiệp/hộ kinh doanh");
            return false;
        }; 
         if (($('#master_print_id').val() == 0)) {
            bootbox.alert("Vui chọn ấn chỉ");
            return false;
        }; 
        if (($('#cobo_id').val() == 0)) {
            bootbox.alert("Vui chọn serial của ấn chỉ");
            return false;
        }; 
         if (($('#jqxDateTimeInput').val() =="")) {
            bootbox.alert("Vui chọn ngày thực hiện");
            return false;
        };
         if (($('#sys_user_id').val() ==0)) {
            bootbox.alert("Vui chọn nhân viên thực hiện");
            return false;
        };
        
      return true;
    }
</script>
<!--<script type="text/javascript">
    function checkinput(){
                var frm = window.document.AddSchedulecheck;    
                var ten = <?php $identity->id?>;
                 bootbox.alert(ten);
                 return false;
            }
</script>-->
<script type="text/javascript">
        $(document).ready(function () {
            $('#a').hide();
             $('#cobo_id').multiselect({
                maxHeight: '300',
                enableFiltering: true,
                maxHeight: '300',
                onChange: function(option, checked) {
                    if (checked) {
                        orderCount++;
                        $(option).data('order', orderCount);
                    }
                    else {
                        $(option).data('order', '');
                    }
                },
            });
        
        $('#cobo_id').on('change', function() {
            var selected = [];
            $('#cobo_id option:selected').each(function() {
                selected.push([$(this).val(), $(this).data('order')]);
            });
 
            selected.sort(function(a, b) {
                return a[1] - b[1];
            });
 
            var text = '';
            for (var i = 0; i < selected.length; i++) {
                text += selected[i][0] + ', ';
            }
            text = text.substring(0, text.length - 2);
 
            $('#selectionlog').val(text);
            $('#selectionlog').text(text);
        });
        });
    </script>