<!DOCTYPE html>
<!--
To change this license header, choose License Headers in Project Properties.
To change this template file, choose Tools | Templates
and open the template in the editor.
-->
<div class="row">
    <div class="col-lg-12">
        <h3 class="page-header">Chỉnh sửa đơn vị</h3>
    </div>    
</div>
<div class="row">
    <div class="col-lg-12">
        <div class="panel panel-default">
            <div class="panel-body">
                <div class="row">
                    <div class="col-lg-12">
                        <form  method="POST" name="Editmasterunit" onsubmit=" return checkinput();">                                    
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Mã Code(*)</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control" name="code" id="code" value="<?php echo $this->item->getCode(); ?>" readonly="true">
                                    </div>
                                    
                                </div>
                            </div>
                            <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Tên đơn vị(*)</label>
                                    </div>
                                    <div class="col-lg-6">
                                        <input class="form-control" name="name" id="name" value="<?php echo $this->item->getName(); ?>">
                                    </div>
                                    
                                </div>
                            </div>
<!--                            <div class="form-group">
                                <div class="row">
                                <div class="col-lg-3">
                                    <label>Thứ tự</label>
                                </div>
                                <div class="col-lg-6">
                                    <input class="form-control" name="order" id="order" value="<?php // echo $this->item->getOrder(); ?>">
                                </div>
                                </div>
                            </div>-->
                             <div class="form-group">
                                    <div class="row">
                                    <div class="col-lg-3">
                                        <label>Ghi chú</label>
                                    </div> 
                                        <div class="col-lg-6">
                                            <textarea  name="comment" id="comment" type="text" class="form-control" cols="100" rows="5"><?php echo $this->item->getComment(); ?></textarea>    
                                        </div>  
                                    </div>                                
                                 </div>
<!--                             <div class="form-group">
                                <div class="row">
                                    <div class="col-lg-3">
                                        <label>Hiển thị</label>
                                    </div>
                                     <div class="col-lg-6">
                                    <input type="checkbox" name="status" id="status_province" value="1" 
                                        <?php // echo ($this->item->getStatus() == 1 ? "checked=\"checked\"" : "") ?> >
                                    </div>
                                    
                                </div>
                            </div>-->
                             <div class="row">
                                <div class="col-lg-6">                      
                                        <div class="form-group">
                                            <div class="row">
                                                 <div class="col-lg-9">
                                                    <button type="submit" name="import" id="import" class="btn btn-primary">Lưu</button>
                                                    <button type="reset" class="btn btn-default">Đặt lại</button> 
                                                 </div>   
                                            </div>
                                        </div> 
                                </div></div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>   
</div>

<script type="text/javascript">
    document.forms['Editmasterunit'].code.focus();
    function set_focus() {
        document.forms['Editmasterunit'].code.focus();
    }
    var flag=true;   
    function checkinput() {
        var frm = window.document.Editmasterunit;
        if (frm.code.value == "") {
            bootbox.alert("Vui lòng nhập mã code");
            return false;
        };
        if (frm.name.value == "") {
            bootbox.alert("Vui lòng nhập tên đơn vị");
            return false;
        };
        
       
      return true;
    }
</script>